apiVersion: v1
data:
  config.yaml: '{"apiVersion":"kubecontrolplane.config.openshift.io/v1","extendedArguments":{"allocate-node-cidrs":["false"],"cert-dir":["/var/run/kubernetes"],"cluster-cidr":["10.128.0.0/14"],"cluster-name":["ocp-rd9g5"],"cluster-signing-cert-file":["/etc/kubernetes/static-pod-certs/secrets/csr-signer/tls.crt"],"cluster-signing-duration":["720h"],"cluster-signing-key-file":["/etc/kubernetes/static-pod-certs/secrets/csr-signer/tls.key"],"configure-cloud-routes":["false"],"controllers":["*","-ttl","-bootstrapsigner","-tokencleaner"],"enable-dynamic-provisioning":["true"],"feature-gates":["APIPriorityAndFairness=true","RotateKubeletServerCertificate=true","DownwardAPIHugePages=true","OpenShiftPodSecurityAdmission=true","RetroactiveDefaultStorageClass=false"],"flex-volume-plugin-dir":["/etc/kubernetes/kubelet-plugins/volume/exec"],"kube-api-burst":["300"],"kube-api-qps":["150"],"leader-elect":["true"],"leader-elect-renew-deadline":["12s"],"leader-elect-resource-lock":["configmapsleases"],"leader-elect-retry-period":["3s"],"pv-recycler-pod-template-filepath-hostpath":["/etc/kubernetes/static-pod-resources/configmaps/recycler-config/recycler-pod.yaml"],"pv-recycler-pod-template-filepath-nfs":["/etc/kubernetes/static-pod-resources/configmaps/recycler-config/recycler-pod.yaml"],"root-ca-file":["/etc/kubernetes/static-pod-resources/configmaps/serviceaccount-ca/ca-bundle.crt"],"secure-port":["10257"],"service-account-private-key-file":["/etc/kubernetes/static-pod-resources/secrets/service-account-private-key/service-account.key"],"service-cluster-ip-range":["172.30.0.0/16"],"use-service-account-credentials":["true"]},"kind":"KubeControllerManagerConfig"}'
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-09T14:22:09Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:config.yaml: {}
    manager: cluster-kube-controller-manager-operator
    operation: Update
    time: "2023-03-09T14:22:09Z"
  name: config
  namespace: openshift-kube-controller-manager
  resourceVersion: "4357"
  uid: 8b35f979-5cf5-4b74-aecd-d5b7f9cf6d3b
