apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMjCCAhqgAwIBAgIIZKwSwwIkBgUwDQYJKoZIhvcNAQELBQAwNzESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSEwHwYDVQQDExhrdWJlLWFwaXNlcnZlci1sYi1zaWduZXIw
    HhcNMjMwMzA5MTQxMDE2WhcNMzMwMzA2MTQxMDE2WjA3MRIwEAYDVQQLEwlvcGVu
    c2hpZnQxITAfBgNVBAMTGGt1YmUtYXBpc2VydmVyLWxiLXNpZ25lcjCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAK9JksvUq0SvxChXYvOE0OoEFRXhBK2J
    eynGjQUJax7xaiY1HFJlAKt3DEo4dLKYrw06kDZ4+jxJvvm0V7MTsvnAYx6Dv0Ft
    hRdNqs+cD8xi9qhyfhL/6xQmiu42UVYg/W9bJaHLzGrYnm80Dk20kOmgHnXRvFAt
    YkJm/PoB+6LTCNKNa+gi6eoV+i7NAMcHgFnVPvRO3ejBdXGd73i2iyFPwacxRGwU
    OdvSyFu26jBNwX8rSPoSbPcsgKOVMnJKeQ58D0Ofo0ONw1AGGiELlvjww9OqFxT/
    HHdx44cq6l30hP6QCzfdfFTC/Gte2LkES6uluWR1thK4FT07V8xY8e8CAwEAAaNC
    MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFP1n
    t4RnO7FvClI9ccGk4g/sbefAMA0GCSqGSIb3DQEBCwUAA4IBAQBZ7B2wUgz8i8rg
    K6xv07ZVal54RsxvgCfk/Q4Le5biFAt6PwyGHG0w2iO4f4EeCClPizGDGIK1aUA9
    5el4CBmVtW6DS6zAXn0Ocv6jbDDpI8WDOQJ6csPXvTCe9kppab6UKh09314athEZ
    tmqw9cB3NKdgV+IEsuvHkqwX/j7oDgPeZHoVG1oUuFK/HMj7dY/SwHFsHqVF5Nkg
    BB+Wfldm+95WVm63MD1NQCeJEdO2hi7xCyk/qSNyU0YdWpTacEuhmdf5oq+FueVX
    9hmwG/m4ARBh4LUdW8Xy74i2B4760iI41i4d7gxcuJIONDbvL5f8aAdJbKDgYe9K
    l3jOtL0Z
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIIP98l+SDqxdEwDQYJKoZIhvcNAQELBQAwPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMB4XDTIzMDMwOTE0MTAxNloXDTMzMDMwNjE0MTAxNlowPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6bBAPMRw9zHl
    CvTa8NwNT8v5TGQXEZiOXKy0R8c2HM54EMtYMwYC1kjsAizyrirMZfRB4c9WTuEp
    gNwJQKTllBs6G1ZnEbSx4SMwtBNe91L39/FXaygLrbirKvnh7D5yOOdbp5P2vOd+
    HgiNVR0igkL4TW4Zx1S4rRhLhnvBOTjs0M18OLUJCi0bnmj4THRAi5u/29QDTQhL
    dXTKgSJ4igy3j21N1j36zWldX6QfjZVWycbBNrZtC7pzJCL5OVelJM0e16Hy33ck
    d+Nw2hWAWhu/68urKNDXB9ZKBI4LBbhzNGq4ClaMgL+3GyS+6IYAoc0sa03CLgUw
    zUUVUfhhxQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQU99fX4oC3DkPafLj71Mn+bmavA2wwDQYJKoZIhvcNAQELBQAD
    ggEBALES6X4nmeoLpKNhvHYU+ILs0qV6gFzAu2ElreiLb6mYHLX72XMNy6bo8iLB
    DgjkDUoucOC/ofJtKfMuUcRqukE3Aql0hXxBi5dZqId2nVTRywww4mpbcH0rtWNl
    TNxj/TOtpAuAJMNmwa4ODbll9fjioOJcXez7YiSkwDmrFzKr5SQNZYYIcyKNTFax
    Lcdc6vf8JMwtxKLnDbURUFQuIG0eMqCGSd6PbuLx37D9W+k3SzTEr27/gxIEtlf5
    mCtzYN11aL2xtN7zE5aBtIUfaGvNKo21bQxnxDIEXUHztoghuBIdffcGG7rWMzKW
    dEuNdtWXmlCLXE+riqidXkk6atk=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIIWghdF9lyqxUwDQYJKoZIhvcNAQELBQAwRDESMBAGA1UE
    CxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2aWNlLW5l
    dHdvcmstc2lnbmVyMB4XDTIzMDMwOTE0MTAxNloXDTMzMDMwNjE0MTAxNlowRDES
    MBAGA1UECxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2
    aWNlLW5ldHdvcmstc2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAzbcs9qsmuCMtk84vZd8oP6jso8CO/+5s+t4vjpJlRcn0Ml/auOfBtbpi/x81
    pjLkygyzafyYHAyjlTrS9nPZ7SU7qfk20oISzKjlIhy/YxqEugB6qYGsN/vR8FcM
    tKBCDCXU/+S00M0rJi9R/HL3l1q6hElilcuLuEpYlZqxND7TsJWGuwK1jApVDeM+
    aVWMzlUtLVs3yVuUGD3W8jIYXi9XNcqWsAwLym7jIbwJF1L3oGZ0D2E8cjQq3upH
    sQPRKv3to/9RskTJwtJMEfFdpR6q4fetBkG2u2VECJzDSWe6sGd0EpZ1O0QkciNV
    /bauXcO8Jk3T30w/eui4G9KIhwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
    VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUfm+tgBNUbtCQsHfm1j4VD7L6jgIwDQYJ
    KoZIhvcNAQELBQADggEBAG9zRFpibBEuT5OOAbj9S7R3N8wHedL6aY7Ljeye48I3
    UokbUw6zhnWF4EkFJOc9vhg66neNdA3IAKYYioHgZWpDvZAkc9B8cDAk9HQuNyYi
    AdsHfiticlXWhC/bNEK5oGmxfj0opUI86GSynTpByu9AzGFcZXJCBlJhXnwKq6Ya
    4KIDt8s64HNeK/gkoUjnXJitPtxTBZ3BXfI9dUt/wlc8RyB1rqV5PiK3CzpDGZxJ
    VEJ4rQ8dQngqtkb9MbCa1I++sFsuUh8J0xclQ6tpDg3lCwKllINon1+/VO6m43ET
    L6rPuQIPOfb3LyPoniKtX58s4uqeBvKyHcxLdmLdo8s=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDlzCCAn+gAwIBAgIIIYJ1NJZZp5kwDQYJKoZIhvcNAQELBQAwWTFXMFUGA1UE
    AwxOb3BlbnNoaWZ0LWt1YmUtYXBpc2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1y
    ZWNvdmVyeS1zZXJ2aW5nLXNpZ25lckAxNjc4MzcyMTM1MB4XDTIzMDMwOTE0Mjg1
    NFoXDTMzMDMwNjE0Mjg1NVowWTFXMFUGA1UEAwxOb3BlbnNoaWZ0LWt1YmUtYXBp
    c2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1yZWNvdmVyeS1zZXJ2aW5nLXNpZ25l
    ckAxNjc4MzcyMTM1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApilE
    qDNrhEZRaBtEADJdlZW9zL7MumKOpJFNUyOC7cVVpNm8Jj72i1Ylx022FZ8bpDBQ
    cwAhwObvNV7bHkobrS4gFsPDUWseNAA9X/rDwIj9ZkHpvgJMVnU4IoMCXgGRqNft
    o2ZdTorIiGYtpawh7RlzlJWoo3iTYpS1J5l+a8nX6kVrlvM0nWWABrRq/nt6pUu8
    /Fer1mH6b3Zw7QjH337cBEBzq73MZaSskNxDM/kzRxJS8hyokuCXhqEdC8963vSw
    SEA+XxTsTvK8kGH8bkUBzIbYZcshdZ+97F3MTyV18K3BfbbMQgIUgMcvgYARvz0h
    Ynf4Jzd4769yVk6c3wIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/
    BAUwAwEB/zAdBgNVHQ4EFgQU/Tl20J77eTm2eu5qugquL2Lanp8wHwYDVR0jBBgw
    FoAU/Tl20J77eTm2eu5qugquL2Lanp8wDQYJKoZIhvcNAQELBQADggEBAA3Ybgao
    mP8F7DeChYKCLLwK9pKkK9d20nSEBws3Uqt+ddXLpMGERsFBArvUBmgeO7bWbcBF
    kFHntGq/sruS5Exc2A6EeCh/nsf6LrgH3Z+4mIrUAkY4As3tOkunZPT7Ddftkf8K
    p2/bQlAl8T2msMvHhdQTvTFVJzaEdh4tNKDHgu+Wrg9S7sBgtxT7vC0Nuh4QRaMt
    ojfL13322wL+ZQDgfR9opd6Z6BdQ07IL1743/qafB8TCNmycqVOpxXfUw9O0FyDN
    FM9VbUa4o0X0Af6E0uh0dyAx3HxoXcAcnMgxlMJo5IAVcPfAz/4fr4eaT8k4BYY9
    pbUmZfIiitnnubY=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDYzCCAkugAwIBAgIIFn129riQe1AwDQYJKoZIhvcNAQELBQAwJjEkMCIGA1UE
    AwwbaW5ncmVzcy1vcGVyYXRvckAxNjc4MzcxNzM4MB4XDTIzMDMwOTE0MjIxOFoX
    DTI1MDMwODE0MjIxOVowITEfMB0GA1UEAwwWKi5hcHBzLm9jcC5jaG9vbWJhLm9u
    ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKho4pc9s84aTlczMHWl
    uFkOFqJCQUGAdzIt2+wL/BXfGPyNVSWODXi3RtdENdTjRTrYf5rMIfzKEywXO3Pd
    ilXE9Uo6HsDt4QoBLbW2PQ5V58wYsV+vEFyUsoFmQGAGPtgIpPKuMFnPc9AL6QIt
    ktipu9EoFyE53RGfdNmUeiOK/v3FqkakPdUhcVbc5ui5hjeRuLYg+O3jcp1esnVu
    C5o7OHGq03xlTlNpC1jghWNQsWWQ1WiquIwtlzw1ZqIOL6QyCvRRolFCQKU125v4
    A+i5FCcVUQs1jQS4UTCZWvr015tkysx3PEsSbbcN8sFkcqIT4WIZQJwUfgg9Da+8
    TX0CAwEAAaOBmTCBljAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUH
    AwEwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU0a8UNWtT4Jes+BAt6azJQChrqGgw
    HwYDVR0jBBgwFoAUMCZehODH8IWU5aJqgUj0UHmtoI4wIQYDVR0RBBowGIIWKi5h
    cHBzLm9jcC5jaG9vbWJhLm9uZTANBgkqhkiG9w0BAQsFAAOCAQEA36loqf5ZKcSH
    v35I/fKQhIkGq2b1u7RmeswUSZDl1TkIv24+nqOUUKjopnsVSLDmktAdLl2Z5SNf
    w4fjUQXaEWjADRd1iw3Kk/5AeFHFNnNfYnh3jcdDxUFBm6aIO/vCgdsottV7iw+G
    0XA+qaI6bCt/vnK/wkOpEy8kNsovucXCBG3qupQT+jykhoWfGVOL7VCAy/o09j9m
    uJKCn35RRySjXlehom8lT3O3iEt8oWsdyWwDesyvyIwQt3WfSH8Ju9joAPDsP7VF
    7ExuVSm20TLYJgG8t8j5Abity3ZZ77cxb9H6f7CrNJLLZSrvN2yBbyc6ehUknido
    g0QA3BSTaA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtpbmdy
    ZXNzLW9wZXJhdG9yQDE2NzgzNzE3MzgwHhcNMjMwMzA5MTQyMjE3WhcNMjUwMzA4
    MTQyMjE4WjAmMSQwIgYDVQQDDBtpbmdyZXNzLW9wZXJhdG9yQDE2NzgzNzE3Mzgw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDogmcWbgUKg5gSL5fgJ3ZR
    9cLnZmz8q3gw5HPpH/cFRriKXNuk894Z+jyrhSOO2ZNdQgH9EQoaOgL7ov5iwW1J
    DRkpR2u6Qo/Kf18wpl5Z6VZQi7INNuh8ANOQaM+c/UpkLT9THsb+NNz1yNPwSPQ5
    mP5wYI9iHyTZxWgOx9EMhRv65Tabqt6sHCnOl9zXlMBjHJBk50YaxfQSwGOLdP67
    g/cYhLBEfggqPXCCjXtWjsd3R+vq3AGeeFnZTLFGAQZtc7ePnV5XKi9CAGit2uMk
    nIyTug2MauWihHOdENsPDqn9yEzlR5vwlWRA1w2UlhlejMU+WvL3GtsRjJ7+AEh9
    AgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICpDASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdDgQWBBQwJl6E4MfwhZTlomqBSPRQea2gjjANBgkqhkiG9w0BAQsFAAOCAQEA
    4zqjJcoIZHIiE2E1lZWQ61k1em6BHqnoN/OIHz0zovf6l4fComwitZoOOWN1jm5L
    0MQsSIuQWvLilZRrMGN5frvQPH2gc8VnWbM44S5gvpfawkZzrRMFVnXYsTJJ7pp1
    eu8vsTqBBgTyXsC2rvVNu17vaIwovD9AzQyYb4Whp2rMkc3xENiedQMkP/GZlFHP
    u3pHCP5s7vM+XnLLx2wmR9s0q/7qwJmz4KSJ55G6HUCssijI631VgPGUS7YMIvWH
    k+n2Oyip4zA3N0zBr1O3Bj4IzAiJB7fRu110GekS+FvNXnB6I/xZm8ApyFjgj5+e
    K0TtS1y8ZfLEMCetfySD0g==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-09T14:37:28Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca-bundle.crt: {}
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"b9b4edf4-e8a6-4aa7-b40d-b692e347e75f"}: {}
    manager: cluster-kube-controller-manager-operator
    operation: Update
    time: "2023-03-09T14:37:28Z"
  name: serviceaccount-ca-6
  namespace: openshift-kube-controller-manager
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: revision-status-6
    uid: b9b4edf4-e8a6-4aa7-b40d-b692e347e75f
  resourceVersion: "17505"
  uid: be337059-7452-4838-bb82-5cce5616b7b5
