apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"vrutkovs-sno_7a0fa6fa-8e9c-46ec-8c7a-627d36916895","leaseDurationSeconds":270,"acquireTime":"2023-03-09T14:28:28Z","renewTime":"2023-03-09T14:35:28Z","leaderTransitions":2}'
  creationTimestamp: "2023-03-09T14:13:49Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:control-plane.alpha.kubernetes.io/leader: {}
    manager: cluster-version-operator
    operation: Update
    time: "2023-03-09T14:35:28Z"
  name: version
  namespace: openshift-cluster-version
  resourceVersion: "17159"
  uid: 8e2ca73f-e91a-45e8-8c4a-afb18b2e19a6
