apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"vrutkovs-sno_38be1e17-2876-49ca-91b0-7fea868ed5bc","leaseDurationSeconds":15,"acquireTime":"2023-03-09T14:30:44Z","renewTime":"2023-03-09T14:31:29Z","leaderTransitions":4}'
  creationTimestamp: "2023-03-09T14:13:46Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:control-plane.alpha.kubernetes.io/leader: {}
    manager: kube-controller-manager
    operation: Update
    time: "2023-03-09T14:31:29Z"
  name: kube-controller-manager
  namespace: kube-system
  resourceVersion: "13041"
  uid: 72427019-bddc-491e-9233-a1da6c0617c9
