apiVersion: v1
data:
  applied: '{"managementState":"Managed","logLevel":"Normal","operatorLogLevel":"Normal","unsupportedConfigOverrides":null,"observedConfig":null,"clusterNetwork":[{"cidr":"10.128.0.0/14","hostPrefix":23}],"serviceNetwork":["172.30.0.0/16"],"defaultNetwork":{"type":"OVNKubernetes","ovnKubernetesConfig":{"mtu":1400,"genevePort":6081,"policyAuditConfig":{"rateLimit":20,"maxFileSize":50,"destination":"null","syslogFacility":"local0"},"egressIPConfig":{}}},"disableMultiNetwork":false,"useMultiNetworkPolicy":false,"deployKubeProxy":false,"disableNetworkDiagnostics":false}'
kind: ConfigMap
metadata:
  creationTimestamp: "2023-03-09T14:20:21Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:applied: {}
      f:metadata:
        f:ownerReferences:
          k:{"uid":"e6519524-ef16-4ee8-82f1-2faa42688032"}: {}
    manager: cluster-network-operator/operconfig
    operation: Apply
    time: "2023-03-09T14:20:21Z"
  name: applied-cluster
  namespace: openshift-network-operator
  ownerReferences:
  - apiVersion: operator.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Network
    name: cluster
    uid: e6519524-ef16-4ee8-82f1-2faa42688032
  resourceVersion: "2534"
  uid: 47afcb03-0383-4c3f-b5cf-6098394f3425
