apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"4b6b7c58-f005-4634-9192-c82dad891643","leaseDurationSeconds":360,"acquireTime":"2023-03-09T14:22:12Z","renewTime":"2023-03-09T14:39:22Z","leaderTransitions":0}'
  creationTimestamp: "2023-03-09T14:22:12Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:control-plane.alpha.kubernetes.io/leader: {}
    manager: cloud-credential-operator
    operation: Update
    time: "2023-03-09T14:39:22Z"
  name: cloud-credential-operator-leader
  namespace: openshift-cloud-credential-operator
  resourceVersion: "17915"
  uid: 99725533-09ba-4f53-b2aa-8b6ac05337d8
